Fix `HTTP status client error (403 Forbidden)` CI errors (#138)
It appears more and more builds fail due to issues with mise
dependencies

```
mise ERROR failed to install aqua:realm/SwiftLint@0.57.0
mise ERROR HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/realm/SwiftLint/releases/tags/0.57.0)
mise ERROR HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/realm/SwiftLint/releases/tags/v0.57.0)
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
make: *** [lint] Error 1
Error: Process completed with exit code 2.
```

The hypothesis is that it's due to GitHub API rate limiting (per IP)

https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

This issue is also mentioned in mise documentation:
https://mise.jdx.dev/getting-started.html#github-api-rate-limiting

Test Plan:
- Ensure all CI checks pass